Many fix
lidofinance/maker-risks-bot pull request #85
Opened 2023-09-20 03:31 UTC by first-leon

Fixed the desynchronization of the alert name and alertmanager parameters.
Fixed an error that occurs in the case of an empty dataframe.
Change alert format.

2023-09-20 07:02 UTC, madlabman requested changes

2023-09-20 07:02 UTC, madlabman commented on src/bot/analytics.py
> +    if not data.empty:
```suggestion
    if not data.empty:
        return pd.DataFrame()
```

2023-09-20 07:02 UTC, madlabman commented on prometheus/zones_changes.rule
>    - name: MakerBot
I see NO tests for the updated rules.

2023-09-20 07:02 UTC, madlabman commented on src/bot/consts.py
> +    HTTP_REQUESTS_DELAY = 3
Move it to `src/bot/config.py`. There are already helpers for env variables.

2023-09-20 07:02 UTC, madlabman commented on src/bot/eth.py
> +w3 = Web3(HTTPProvider(NODE_ENDPOINT, request_kwargs={'timeout': 90}))
Run `black` please.

2023-10-03 11:31 UTC, madlabman commented on src/bot/config.py
> +    HTTP_REQUESTS_RETRY = 3
```suggestion
HTTP_REQUESTS_RETRY = getenv("HTTP_REQUESTS_RETRY", int, default=3)
```

and the same for the one below

2023-10-03 12:44 UTC, madlabman approved these changes

2023-10-03 17:14 UTC, PavelPoddubnyi approved these changes

2023-10-03 17:14 UTC, merged